// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//VerifiedClaims
export const GET_VERIFIED_REQUEST = 'GET_VERIFIED_REQUEST';
export const GET_VERIFIED_REQUEST_SUCCESS = 'GET_VERIFIED_REQUEST_SUCCESS';

//UnverifiedClaims
export const GET_UNVERIFIED_REQUEST = 'GET_UNVERIFIED_REQUEST';
export const GET_UNVERIFIED_REQUEST_SUCCESS = 'GET_UNVERIFIED_REQUEST_SUCCESS';

//Rejected Claims
export const GET_REJECTEDCLAIM_REQUEST = 'GET_REJECTEDCLAIM_REQUEST';
export const GET_REJECTEDCLAIM_REQUEST_SUCCESS = 'GET_REJECTEDCLAIM_REQUEST_SUCCESS';


//Verify Claim Action
export const VERIFYCLAIM_ACTION = 'VERIFYCLAIM_ACTION';
export const VERIFYCLAIM_ACTION_SUCCESS = 'VERIFYCLAIM_ACTION_SUCCESS';

//const Add Claim
export const ADD_CLAIM = 'ADD_CLAIM';

//const Update auth
export const UPDATE_AUTH = 'UPDATE_AUTH';

